### ISSUE TITLE
Use docker profiles to simplify compose file

### ISSUE THREAD

**Issue by ghost** [i-dot-ai/redbox#189]
The docker compose file is quite confusing and unintuitive. We can use [profiles](https://docs.docker.com/compose/profiles/) to make the compose explicitly group services to match they way the dev team are mentally grouping them. This will also make integration testing easier, as the function of the groups is abstracted away from the services that actually make it up.

I suggest broad groups of `backend` and `frontend_*`, for example:

```console
docker compose --profile backend --profile frontend_streamlit up
```

```console
docker compose --profile backend --profile frontend_django up
```

**Comment by gecBurton** [comment]
@wpfl-dbt thank you for raising this, we will discuss at sprint planning on the 2024/04/10
