### ISSUE TITLE
[AWS SUPPORT] Allow Custom Configuration of Additional Hosts via Environment Variables

### ISSUE THREAD

**Issue by tom1322s** [i-dot-ai/redbox#763]
Description:
Currently, the list of additional hosts in the application is hardcoded, as seen in the [setting_enums.py](https://github.com/i-dot-ai/redbox/blob/main/django_app/redbox_app/setting_enums.py#L20C1-L25C1) file. This setup limits flexibility and makes it difficult to manage configurations, especially in dynamic environments like AWS.

Proposed Solution:
Introduce the ability to set a custom list of additional hosts using environment variables. This change will enhance the configurability of the application, allowing users to define and modify the list of additional hosts through environment variables, thereby improving the application's adaptability to various deployment scenarios.

**Comment by gecBurton** [comment]
@tom1322s we will do this this week

**Comment by brunns** [comment]
Fixed by #791
